const sidebars = {
  mainSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Diagramas',
      link: { type: 'doc', id: 'diagramas/index' },
      items: [
      ],
    },
    {
      type: 'category',
      label: 'Esquemas',
      link: { type: 'doc', id: 'esquemas/index' },
      items: [
        'esquemas/cob_cuentas',
        'esquemas/cob_pagos',
        'esquemas/cob_remesas',
        'esquemas/cobis',
        'esquemas/public',
      ],
    },
    {
      type: 'category',
      label: 'Estandares',
      link: { type: 'doc', id: 'estandares/index' },
      items: [
        'estandares/sybase-sqlserver',
        'estandares/oracle',
        'estandares/anexos',
        'estandares/control-cambios',
      ],
    },
    {
      type: 'category',
      label: 'Migraciones',
      link: { type: 'doc', id: 'migraciones/index' },
      items: [
      ],
    },
    {
      type: 'category',
      label: 'Procedimientos',
      link: { type: 'doc', id: 'procedimientos/index' },
      items: [
        'procedimientos/cobis/cobis_pa_con_ccertificado_pagos_gen',
        'procedimientos/cobis/cobis_pa_con_tult_dia_habil_ant',
        'procedimientos/cobis/cobis_pa_mis_ttelefono',
        'procedimientos/cobis/cobis_pa_pg_tpag_reca_varios',
        'procedimientos/public/public_akeys',
        'procedimientos/public/public_array_to_halfvec',
        'procedimientos/public/public_array_to_sparsevec',
        'procedimientos/public/public_array_to_vector',
        'procedimientos/public/public_avals',
        'procedimientos/public/public_binary_quantize',
        'procedimientos/public/public_cosine_distance',
        'procedimientos/public/public_defined',
        'procedimientos/public/public_delete',
        'procedimientos/public/public_each',
        'procedimientos/public/public_exist',
        'procedimientos/public/public_exists_all',
        'procedimientos/public/public_exists_any',
        'procedimientos/public/public_fetchval',
        'procedimientos/public/public_ghstore_compress',
        'procedimientos/public/public_ghstore_consistent',
        'procedimientos/public/public_ghstore_decompress',
        'procedimientos/public/public_ghstore_in',
        'procedimientos/public/public_ghstore_options',
        'procedimientos/public/public_ghstore_out',
        'procedimientos/public/public_ghstore_penalty',
        'procedimientos/public/public_ghstore_picksplit',
        'procedimientos/public/public_ghstore_same',
        'procedimientos/public/public_ghstore_union',
        'procedimientos/public/public_gin_consistent_hstore',
        'procedimientos/public/public_gin_extract_hstore',
        'procedimientos/public/public_gin_extract_hstore_query',
        'procedimientos/public/public_halfvec',
        'procedimientos/public/public_halfvec_accum',
        'procedimientos/public/public_halfvec_add',
        'procedimientos/public/public_halfvec_avg',
        'procedimientos/public/public_halfvec_cmp',
        'procedimientos/public/public_halfvec_combine',
        'procedimientos/public/public_halfvec_concat',
        'procedimientos/public/public_halfvec_eq',
        'procedimientos/public/public_halfvec_ge',
        'procedimientos/public/public_halfvec_gt',
        'procedimientos/public/public_halfvec_in',
        'procedimientos/public/public_halfvec_l2_squared_distance',
        'procedimientos/public/public_halfvec_le',
        'procedimientos/public/public_halfvec_lt',
        'procedimientos/public/public_halfvec_mul',
        'procedimientos/public/public_halfvec_ne',
        'procedimientos/public/public_halfvec_negative_inner_product',
        'procedimientos/public/public_halfvec_out',
        'procedimientos/public/public_halfvec_recv',
        'procedimientos/public/public_halfvec_send',
        'procedimientos/public/public_halfvec_spherical_distance',
        'procedimientos/public/public_halfvec_sub',
        'procedimientos/public/public_halfvec_to_float4',
        'procedimientos/public/public_halfvec_to_sparsevec',
        'procedimientos/public/public_halfvec_to_vector',
        'procedimientos/public/public_halfvec_typmod_in',
        'procedimientos/public/public_hamming_distance',
        'procedimientos/public/public_hnsw_bit_support',
        'procedimientos/public/public_hnsw_halfvec_support',
        'procedimientos/public/public_hnsw_sparsevec_support',
        'procedimientos/public/public_hnswhandler',
        'procedimientos/public/public_hs_concat',
        'procedimientos/public/public_hs_contained',
        'procedimientos/public/public_hs_contains',
        'procedimientos/public/public_hstore',
        'procedimientos/public/public_hstore_cmp',
        'procedimientos/public/public_hstore_eq',
        'procedimientos/public/public_hstore_ge',
        'procedimientos/public/public_hstore_gt',
        'procedimientos/public/public_hstore_hash',
        'procedimientos/public/public_hstore_hash_extended',
        'procedimientos/public/public_hstore_in',
        'procedimientos/public/public_hstore_le',
        'procedimientos/public/public_hstore_lt',
        'procedimientos/public/public_hstore_ne',
        'procedimientos/public/public_hstore_out',
        'procedimientos/public/public_hstore_recv',
        'procedimientos/public/public_hstore_send',
        'procedimientos/public/public_hstore_subscript_handler',
        'procedimientos/public/public_hstore_to_array',
        'procedimientos/public/public_hstore_to_json',
        'procedimientos/public/public_hstore_to_json_loose',
        'procedimientos/public/public_hstore_to_jsonb',
        'procedimientos/public/public_hstore_to_jsonb_loose',
        'procedimientos/public/public_hstore_to_matrix',
        'procedimientos/public/public_hstore_version_diag',
        'procedimientos/public/public_inner_product',
        'procedimientos/public/public_isdefined',
        'procedimientos/public/public_isexists',
        'procedimientos/public/public_ivfflat_bit_support',
        'procedimientos/public/public_ivfflat_halfvec_support',
        'procedimientos/public/public_ivfflathandler',
        'procedimientos/public/public_jaccard_distance',
        'procedimientos/public/public_l1_distance',
        'procedimientos/public/public_l2_distance',
        'procedimientos/public/public_l2_norm',
        'procedimientos/public/public_l2_normalize',
        'procedimientos/public/public_populate_record',
        'procedimientos/public/public_skeys',
        'procedimientos/public/public_slice',
        'procedimientos/public/public_slice_array',
        'procedimientos/public/public_sparsevec',
        'procedimientos/public/public_sparsevec_cmp',
        'procedimientos/public/public_sparsevec_eq',
        'procedimientos/public/public_sparsevec_ge',
        'procedimientos/public/public_sparsevec_gt',
        'procedimientos/public/public_sparsevec_in',
        'procedimientos/public/public_sparsevec_l2_squared_distance',
        'procedimientos/public/public_sparsevec_le',
        'procedimientos/public/public_sparsevec_lt',
        'procedimientos/public/public_sparsevec_ne',
        'procedimientos/public/public_sparsevec_negative_inner_product',
        'procedimientos/public/public_sparsevec_out',
        'procedimientos/public/public_sparsevec_recv',
        'procedimientos/public/public_sparsevec_send',
        'procedimientos/public/public_sparsevec_to_halfvec',
        'procedimientos/public/public_sparsevec_to_vector',
        'procedimientos/public/public_sparsevec_typmod_in',
        'procedimientos/public/public_subvector',
        'procedimientos/public/public_svals',
        'procedimientos/public/public_tconvert',
        'procedimientos/public/public_uuid_generate_v1',
        'procedimientos/public/public_uuid_generate_v1mc',
        'procedimientos/public/public_uuid_generate_v3',
        'procedimientos/public/public_uuid_generate_v4',
        'procedimientos/public/public_uuid_generate_v5',
        'procedimientos/public/public_uuid_nil',
        'procedimientos/public/public_uuid_ns_dns',
        'procedimientos/public/public_uuid_ns_oid',
        'procedimientos/public/public_uuid_ns_url',
        'procedimientos/public/public_uuid_ns_x500',
        'procedimientos/public/public_vector',
        'procedimientos/public/public_vector_accum',
        'procedimientos/public/public_vector_add',
        'procedimientos/public/public_vector_avg',
        'procedimientos/public/public_vector_cmp',
        'procedimientos/public/public_vector_combine',
        'procedimientos/public/public_vector_concat',
        'procedimientos/public/public_vector_dims',
        'procedimientos/public/public_vector_eq',
        'procedimientos/public/public_vector_ge',
        'procedimientos/public/public_vector_gt',
        'procedimientos/public/public_vector_in',
        'procedimientos/public/public_vector_l2_squared_distance',
        'procedimientos/public/public_vector_le',
        'procedimientos/public/public_vector_lt',
        'procedimientos/public/public_vector_mul',
        'procedimientos/public/public_vector_ne',
        'procedimientos/public/public_vector_negative_inner_product',
        'procedimientos/public/public_vector_norm',
        'procedimientos/public/public_vector_out',
        'procedimientos/public/public_vector_recv',
        'procedimientos/public/public_vector_send',
        'procedimientos/public/public_vector_spherical_distance',
        'procedimientos/public/public_vector_sub',
        'procedimientos/public/public_vector_to_float4',
        'procedimientos/public/public_vector_to_halfvec',
        'procedimientos/public/public_vector_to_sparsevec',
        'procedimientos/public/public_vector_typmod_in',
      ],
    },
    {
      type: 'category',
      label: 'Secuencias',
      link: { type: 'doc', id: 'secuencias/index' },
      items: [
        'secuencias/cobis/cobis_tmp_log_phol2_id_seq',
        'secuencias/cobis/cobis_ts_telefono_id_seq',
      ],
    },
    {
      type: 'category',
      label: 'Tablas',
      link: { type: 'doc', id: 'tablas/index' },
      items: [
        'tablas/cobis/cobis_ba_fecha_proceso',
        'tablas/cobis/cobis_cl_catalogo',
        'tablas/cobis/cobis_cl_ciudad',
        'tablas/cobis/cobis_cl_dias_feriados',
        'tablas/cobis/cobis_cl_direccion',
        'tablas/cobis/cobis_cl_direccion_email',
        'tablas/cobis/cobis_cl_ente',
        'tablas/cobis/cobis_cl_oficina',
        'tablas/cobis/cobis_cl_parametro',
        'tablas/cobis/cobis_cl_producto',
        'tablas/cobis/cobis_cl_tabla',
        'tablas/cobis/cobis_cl_telefono',
        'tablas/cobis/cobis_cl_ttransaccion',
        'tablas/cobis/cobis_tmp_log_phol2',
        'tablas/cobis/cobis_ts_telefono',
        'tablas/cob_cuentas/cob_cuentas_cc_dias_laborables',
        'tablas/cob_cuentas/cob_cuentas_cc_tran_servicio',
        'tablas/cob_cuentas/cob_cuentas_cc_tran_servicio_resp',
        'tablas/cob_pagos/cob_pagos_pg_person_empresa',
        'tablas/cob_remesas/cob_remesas_re_horario',
        'tablas/public/public_vector_store',
      ],
    },
  ],
};
module.exports = sidebars;
