-- cob_pagos.dbo.cc_tran_servicio definition

-- Drop table

-- DROP TABLE cob_pagos.dbo.cc_tran_servicio;

CREATE TABLE cob_pagos.dbo.cc_tran_servicio (
  ts_secuencial int NOT NULL,
  ts_cod_alterno int NULL,
  ts_tipo_transaccion int NOT NULL,
  ts_clase varchar(3) NULL,
  ts_tsfecha smalldatetime NOT NULL,
  ts_tabla tinyint NULL,
  ts_usuario descripcion NULL,
  ts_terminal descripcion NULL,
  ts_rol smallint NULL,
  ts_correccion char(1) NULL,
  ts_ssn_corr int NULL,
  ts_reentry char(1) NULL,
  ts_origen char(1) NULL,
  ts_nodo varchar(30) NULL,
  ts_referencia varchar(15) NULL,
  ts_remoto_ssn int NULL,
  ts_cheque_rec int NULL,
  ts_ctacte int NULL,
  ts_cta_banco cuenta NULL,
  ts_filial tinyint NULL,
  ts_oficina smallint NULL,
  ts_oficial smallint NULL,
  ts_fecha_aper smalldatetime NULL,
  ts_cliente int NULL,
  ts_ced_ruc numero NULL,
  ts_estado char(1) NULL,
  ts_direccion_ec tinyint NULL,
  ts_descripcion_ec direccion NULL,
  ts_ciclo char(1) NULL,
  ts_categoria char(1) NULL,
  ts_producto tinyint NULL,
  ts_tipo char(1) NULL,
  ts_indicador tinyint NULL,
  ts_moneda tinyint NULL,
  ts_default int NULL,
  ts_tipo_def char(1) NULL,
  ts_rol_ente char(1) NULL,
  ts_tipo_promedio char(1) NULL,
  ts_numero smallint NULL,
  ts_fecha smalldatetime NULL,
  ts_autorizante descripcion NULL,
  ts_causa varchar(6) NULL,
  ts_servicio varchar(3) NULL,
  ts_saldo money NULL,
  ts_fecha_uso smalldatetime NULL,
  ts_monto money NULL,
  ts_fecha_ven smalldatetime NULL,
  ts_filial_aut tinyint NULL,
  ts_ofi_aut tinyint NULL,
  ts_autoriz_aut descripcion NULL,
  ts_filial_anula tinyint NULL,
  ts_ofi_anula tinyint NULL,
  ts_autoriz_anula descripcion NULL,
  ts_cheque_desde int NULL,
  ts_cheque_hasta int NULL,
  ts_chequera smallint NULL,
  ts_num_cheques smallint NULL,
  ts_departamento smallint NULL,
  ts_cta_gir cuenta NULL,
  ts_endoso int NULL,
  ts_cod_banco varchar(8) NULL,
  ts_corresponsal varchar(8) NULL,
  ts_propietario varchar(8) NULL,
  ts_carta int NULL,
  ts_sec_correccion int NULL,
  ts_cheque int NULL,
  ts_cta_banco_dep cuenta NULL,
  ts_oficina_pago smallint NULL,
  ts_contratado money NULL,
  ts_valor money NULL,
  ts_ocasional money NULL,
  ts_banco smallint NULL,
  ts_ccontable varchar(20) NULL,
  ts_cta_funcionario char(1) NULL,
  ts_mercantil char(1) NULL,
  ts_cta_asociada cuenta NULL,
  ts_tipocta char(1) NULL,
  ts_fecha_eimp smalldatetime NULL,
  ts_fecha_rimp smalldatetime NULL,
  ts_fecha_rofi smalldatetime NULL,
  ts_tipo_chequera varchar(5) NULL,
  ts_stick_imp char(12) NULL,
  ts_tipo_imp char(1) NULL,
  ts_tarjcred varchar(20) NULL,
  ts_aporte_iess money NULL,
  ts_descuento_iess money NULL,
  ts_fonres_iess money NULL,
  ts_agente varchar(30) NULL,
  ts_nombre direccion NULL,
  ts_debito char(1) NULL,
  ts_hora smalldatetime NULL,
  ts_oficina_cta smallint NULL,
  ts_tsn int NULL,
  ts_tipo_contable char(2) NULL,
  ts_estado_sob char(3) NULL,
  ts_tipo_credito char(1) NULL,
  ts_plazo char(2) NULL,
  ts_tipo_sobregiro char(1) NULL,
  ts_campo_alt_uno varchar(30) NULL,
  ts_campo_alt_dos varchar(30) NULL,
  ts_ubicacion smallint NULL,
  [ts_monto (debito)] money NULL,
  [ts_valor (efectivo)] money NULL,
  [ts_contratado (tc)] money NULL
);